kind: ConfigMap
metadata:
  name: kafka-mqtt-connect-config
apiVersion: v1
data:
  mqtt.properties: |-
    # From k8s ConfigMap
    ##
    # Basic
    ##
    name=mqtt
    connector.class=com.evokly.kafka.connect.mqtt.MqttSourceConnector
    tasks.max=1
    #Settings
    # Where to put processed messages - default to `mqtt`
    kafka.topic=mqtt-test
    # What client id to use - defaults to `null` which means random client_id
    mqtt.client_id=mqtt-kafka-test
    # Use clean session in connection? - default `true`
    #mqtt.clean_session=true
    # What mqtt connection timeout to use - defaults to `30` seconds
    #mqtt.connection_timeout=30
    # What mqtt connection keep alive to use - defaults to `60` seconds
    #mqtt.keep_alive_interval=60
    # Mqtt broker address to use - defaults to `tcp://localhost:1883`
    # if using TLS then certs can be used
    mqtt.server_uris=tcp://mqtt-svc:1883
    # Mqtt topic to listen to - defaults to `#` (wildcard - all)
    mqtt.topic=paho/test/simple
    # Mqtt QoS to use - defaults to 1
    #mqtt.qos=1
    # CA cert to use to connect to mqtt broker, can be used when connecting to TLS secured brokers - default `null`
    #mqtt.ssl.ca_cert=null
    # Client cert to use to connect to mqtt broker, can be used when connecting to TLS secured brokers - default `null`
    #mqtt.ssl.cert=null
    # Client key to use to connect to mqtt broker, can be used when connecting to TLS secured brokers - default `null`
    #mqtt.ssl.key=null
    # Username to use to connect to mqtt broker - default `null`
    #mqtt.user=null
    # Username to use to connect to mqtt broker - default `null`
    #mqtt.password=null
    # Message processor class to use to process mqtt messages before puting them on kafka - defaults to samle `DumbProcessor`
    #message_processor_class=com.evokly.kafka.connect.mqtt.sample.DumbProcessor
  
  connect-standalone.properties: |-
    # From k8s ConfigMap
    # Licensed to the Apache Software Foundation (ASF) under one or more
    # contributor license agreements.  See the NOTICE file distributed with
    # this work for additional information regarding copyright ownership.
    # The ASF licenses this file to You under the Apache License, Version 2.0
    # (the "License"); you may not use this file except in compliance with
    # the License.  You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.

    # These are defaults. This file just demonstrates how to override some settings.
    bootstrap.servers=kafka-0.broker.kafka.svc.cluster.local:9092

    # The converters specify the format of data in Kafka and how to translate it into Connect data. Every Connect user will
    # need to configure these based on the format they want their data in when loaded from or stored into Kafka
    key.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter=org.apache.kafka.connect.json.JsonConverter
    # Converter-specific settings can be passed in by prefixing the Converter's setting with the converter we want to apply
    # it to
    key.converter.schemas.enable=true
    value.converter.schemas.enable=true

    # The internal converter used for offsets and config data is configurable and must be specified, but most users will
    # always want to use the built-in default. Offset and config data is never visible outside of Kafka Connect in this format.
    internal.key.converter=org.apache.kafka.connect.json.JsonConverter
    internal.value.converter=org.apache.kafka.connect.json.JsonConverter
    internal.key.converter.schemas.enable=false
    internal.value.converter.schemas.enable=false

    offset.storage.file.filename=/tmp/connect.offsets
    # Flush much faster than normal, which is useful for testing/debugging
    offset.flush.interval.ms=10000

    # Set to a list of filesystem paths separated by commas (,) to enable class loading isolation for plugins
    # (connectors, converters, transformations). The list should consist of top level directories that include 
    # any combination of: 
    # a) directories immediately containing jars with plugins and their dependencies
    # b) uber-jars with plugins and their dependencies
    # c) directories immediately containing the package directory structure of classes of plugins and their dependencies
    # Note: symlinks will be followed to discover dependencies or plugins.
    # Examples: 
    # plugin.path=/usr/local/share/java,/usr/local/share/kafka/plugins,/opt/connectors,
    #plugin.path=
